services:
  api:
    build: 
      context: ./engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./engine:/app
      - chromadata:/app/chromadata
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    # Descomente o bloco abaixo caso tenha GPU NVIDIA e queira acelerar o Whisper
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    # Descomente o bloco abaixo caso tenha GPU NVIDIA e queira acelerar o Ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  chromadata:
  ollama_models:
